context:
  version: 2.2.13

package:
  name: indent
  version: ${{ version }}

source:
  url: https://ftp.gnu.org/gnu/indent/indent-${{ version }}.tar.gz
  sha256: 9e64634fc4ce6797b204bcb8897ce14fdd0ab48ca57696f78767c59cae578095

build:
  number: 0
  skip: win

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - make
    - pkg-config
    - sed
    - texinfo
  host:
    - gettext

tests:
  - script:
      - indent --help 2>&1 | grep -q "usage: "indent\""

about:
  license: GPL-3.0-or-later
  license_file: COPYING
  summary: C code prettifier
  homepage: https://www.gnu.org/software/indent

extra:
  recipe-maintainers:
    - danielnachun
